In [15]:
import pandas as pd
from functions.sleeper_functions import *
import datetime as datetime
import numpy as np

In [16]:
slot_table = pd.read_csv('Files/working/slots_2021.csv', dtype='object')
len(slot_table)

128328

In [17]:
completed_results = pd.read_csv('Files/working/results_2021.csv', dtype='object')
len(completed_results)

115400

In [18]:
df = completed_results.append(slot_table)
len(df)

243728

In [19]:
tdf = df.drop_duplicates(subset=['league_id','user_id'])
tdf = tdf[tdf['wins'].isnull()]
len(tdf)

13331

In [20]:
truns = tdf[['league_id','draft_id']].drop_duplicates().reset_index(drop=True)

In [21]:
truns

               league_id            draft_id
0     754346249192386560  754346250568126464
1     739213526450749440  739213526983446528
2     735232524091023360  735232525387083776
3     726148600127688704  726148600127688705
4     739195704957874176  739195706031833088
...                  ...                 ...
1304  731895089164603392  731895089944723456
1305  767476687314202625  767476690623549440
1306  727973179301146624  727973180165128192
1307  726458589945905152  726458591300665344
1308  723353418940407808  723353420030914560

[1309 rows x 2 columns]

In [22]:
conn = http.client.HTTPSConnection('api.sleeper.app')

results = pd.DataFrame()
picks = pd.DataFrame()

i = 0

limit = 1309
marker = 100

for index, row in truns[:limit].iterrows():
    
    i += 1
    if i%marker == 0:
        print("-- "+str(i)+'/'+str(limit))
    
    league_id = row['league_id']
    draft_id = row['draft_id']
    try:
                # league results
        conn = http.client.HTTPSConnection('api.sleeper.app')
        conn.request("GET", '/v1/league/' + str(league_id) + '/rosters/')
        start_conn = conn.getresponse().read()
        data = json.loads(start_conn)
        df = pd.json_normalize(data)
        df = df[['owner_id','settings.total_moves','settings.wins','settings.ties','settings.losses', 'settings.fpts']]
        df['wins'] = df['settings.wins'] + (.5 * df['settings.ties'])
        df['points_standing'] = df['settings.fpts'].rank(ascending=False)
        df['season_standing'] = df[["wins","settings.fpts"]].apply(tuple,axis=1)\
                     .rank(method='dense',ascending=False).astype(int)
        df = df[['owner_id','settings.total_moves','settings.fpts', 'wins', 'points_standing','season_standing']]
        df.columns = ['user_id','total_moves', 'season_points','wins','points_standing','season_standing']
        df['league_id'] = league_id
        results = results.append(df)
    except:
        pass

-- 100/1309
-- 200/1309
-- 300/1309
-- 400/1309
-- 500/1309
-- 600/1309
-- 700/1309
-- 800/1309
-- 900/1309
-- 1000/1309
-- 1100/1309
-- 1200/1309
-- 1300/1309

In [9]:
slots = slot_table.merge(results, on=['user_id','league_id'], how='left').drop_duplicates()

In [10]:
t1 = slots[~slots['wins'].isnull()]

In [11]:
t1

,slot,user_id,league_id,status,draft_id,draft_type,season,scoring_type,last_update_dt,total_moves,season_points,wins,points_standing,season_standing
1404,8,746112158995193856,754346249192386560,complete,754346250568126464,snake,2021,2qb,2022-08-19 10:21:17.939563,0.0,1708.0,9.0,1.0,2.0
1405,10,741320819933925376,754346249192386560,complete,754346250568126464,snake,2021,2qb,2022-08-19 10:21:17.939563,0.0,1598.0,11.0,2.0,1.0
1406,3,741046390297403392,754346249192386560,complete,754346250568126464,snake,2021,2qb,2022-08-19 10:21:17.939563,0.0,328.0,4.0,7.0,9.0
1408,4,733518334116663296,754346249192386560,complete,754346250568126464,snake,2021,2qb,2022-08-19 10:21:17.939563,0.0,526.0,4.5,6.0,7.0
1409,7,731327844512284672,754346249192386560,complete,754346250568126464,snake,2021,2qb,2022-08-19 10:21:17.939563,0.0,600.0,5.0,5.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115139,2,731565659896569856,731564818632384512,complete,731564819718782976,snake,2021,ppr,2022-08-19 12:58:04.362803,0.0,1976.0,8.0,4.0,4.0
115140,3,731564468143767552,731564818632384512,complete,731564819718782976,snake,2021,ppr,2022-08-19 12:58:04.362803,0.0,1700.0,5.0,10.0,9.0
115141,6,731563641425469440,731564818632384512,complete,731564819718782976,snake,2021,ppr,2022-08-19 12:58:04.362803,0.0,1947.0,7.0,5.0,6.0
115142,4,731563096035946496,731564818632384512,complete,731564819718782976,snake,2021,ppr,2022-08-19 12:58:04.362803,0.0,2008.0,7.0,2.5,5.0
115143,7,708106153497825280,731564818632384512,complete,731564819718782976,snake,2021,ppr,2022-08-19 12:58:04.362803,0.0,1716.0,3.0,9.0,10.0

In [12]:
t3 = completed_results.append(t1)

In [13]:
t3 = t3.drop_duplicates()

In [14]:
t3.dropna(subset=['wins']).to_csv('Files/working/results_2021.csv',index=False)